### ISSUE TITLE
v1.1.2 release?

### ISSUE THREAD

**Issue by manuelpuyol** [FormidableLabs/prism-react-renderer#109]
Hello 👋 

Would it be possible to create a new release with the changes in `master`?

https://github.com/FormidableLabs/prism-react-renderer/pull/105
https://github.com/FormidableLabs/prism-react-renderer/pull/103
https://github.com/FormidableLabs/prism-react-renderer/pull/95
https://github.com/FormidableLabs/prism-react-renderer/pull/83

**Comment by kitten** [comment]
Yes, I'll create a release as soon as I find time to review what has been done, look whether I can cherry-pick the remaining PR, compile a changelog, and see whether I'd like to make other changes while I'm issuing a release or upgrade anything related, like the Rollup build.

I'll have to carve out some time for that, so please have some patience 😅 I'm closing this since issues for releases aren't really addressable or issues per se 💟 

Also, on a side note, this will likely be a minor bump not a patch bump due to additions.

**Comment by yakkomajuri** [comment]
+1 for this

**Comment by kitten** [comment]
Just got this done; haven't quite tested it yet for regressions but all changes have been incorporated https://github.com/FormidableLabs/prism-react-renderer/releases/tag/v1.2.0

**Comment by yakkomajuri** [comment]
Awesome, thanks! I'll reference this on [our website](https://github.com/PostHog/posthog.com) and report back if it breaks anything 😄
