### ISSUE TITLE
Bump Prism version

### ISSUE THREAD

**Issue by marcospassos** [FormidableLabs/prism-react-renderer#125]
This package currently uses an old version of the PrimJS that was released back in December 2020. A lot of new cool features have been added since then, such as an HTML attribute highlighting.

Is there anything preventing bumping the version?

**Comment by Josh-Cena** [comment]
Theoretically we can pass in a custom Prism instance, but I've been unable to get it working. In any case, I hope this lib can be more maintained than it appears currently...

**Comment by darach** [comment]
Prism is now the default highlighter supported out of the box with `docusaurus` - a more recent version of this renderer would be great as it would avoid having to fork and maintain the renderer and customize docusaurus. It would be great to see an update so that projects using `docusaurus` ( like ours ) - can use recent fixes improvements and the language definitions available in prism since the last release of this package.

**Comment by Josh-Cena** [comment]
@darach Docusaurus is now more proactive at forking pseudo-dead / dead dependencies, so if there's a strong incentive you can open a request in our repo and ask us to fork it. (We will soon have a docusaurus-core organization to store these deps.)

**Comment by darach** [comment]
@Josh-Cena Thanks for responding so quickly and reaching out - we'll open an issue later this evening 👍

**Comment by jpdriver** [comment]
hey all 👋🏻 this was addressed in https://github.com/FormidableLabs/prism-react-renderer/pull/139 and as of `prism-react-renderer@1.3.0` we now use `prismjs@1.26.0` behind the scenes (latest available at time of writing)

it is still a vendored version with only a subset of the available grammars enabled though; so please open a separate issue if some specific thing isn't working 😅
