### ISSUE TITLE
Add Flow types to the package

### ISSUE THREAD

**Issue by alexkirsz** [FormidableLabs/prism-react-renderer#13]
Hey,

I'm trying to use this module in a project where Flow is enabled, but I'm getting the following error:

```
Error ------------------------------------------------------------------------------------------------------------------
node_modules/prism-react-renderer/themes/vsDark.js:4:38

Cannot resolve module ../src/types.

     1| // @flow
     2| // Converted automatically using ./tools/themeFromVsCode
     3|
     4| /*:: import type { PrismTheme } from '../src/types' */
     5|
     6| var theme /*: PrismTheme */ = {
     7|   plain: {
```

The src/types folder isn't part of the NPM package.

Alex

**Comment by kitten** [comment]
There's no correct flow-types that are exposed on this package yet, so I'd recommend to ignore the module entirely for now.

The reason why there's no exposed types is intentional. Generally tools like flow-copy-source and other solutions that just _expose_ existing flow types don't work very well. Hence it's advisable to only expose the types and write some manual typings for everything else, in my experience.

**Comment by alexkirsz** [comment]
What's the reasoning behind adding type annotations to the themes under themes/ if we can't consume them properly for now? Wouldn't it be better to remove those annotations until such a time that the types they use are shipped alongside them?

**Comment by Powell-v2** [comment]
Hi there,

Do you still need help with this?
