### ISSUE TITLE
Prism.languages['markup-templating'] is undefined

### ISSUE THREAD

**Issue by guoyunhe** [FormidableLabs/prism-react-renderer#152]
After update to 1.3.2 today, it always throws error:

![image](https://user-images.githubusercontent.com/5836790/168516735-7badf76b-a17e-4ab1-b310-26a7d2ee124a.png)

![image](https://user-images.githubusercontent.com/5836790/168516826-d697f97c-c3ed-4720-b51b-efccee6296e8.png)

Debugging found that Prism.languages['markup-templating'] is undefined.

I believe it is introduced by #151 

CC @jpdriver

**Comment by cndlhvn** [comment]
me too

**Comment by Josh-Cena** [comment]
Yes, this is happening with Docusaurus as well. https://github.com/facebook/docusaurus/issues/7429

**Comment by maoxiaoke** [comment]
+1

**Comment by jpdriver** [comment]
sorry all!

with the logic introduced in #151 we now account for `optional` dependencies of each language. however in the course of working on this, i noticed that these changes added a bunch of new grammars that weren't there before.

i thought it would be a good idea to add a restriction so that we restrict it to the same set of grammars (based on `includedLangs`) as previous versions -- and `markdown-templating` fell into this trap as it wasn't listed in our `includedLangs` 🤦🏻‍♂️ 

many thanks for the quick report!

**Comment by Josh-Cena** [comment]
I can confirm 1.3.3 works and the Markdown front matter highlighting is properly applied without hacks. Thanks for the swift response @jpdriver and the nice work in #151!
