### ISSUE TITLE
Add docker and shell-session language support

### ISSUE THREAD

**Issue by schultzp2020** [FormidableLabs/prism-react-renderer#162]
# Feature request

Docker and shell-session are common enough languages that they should be supported without needing to add the language manually.

**Comment by jpdriver** [comment]
hey @schultzp2020 -- we decided on the list of default languages because those are the ones we see the most demand for from users of our other OSS projects which consume `prism-react-renderer` (primarily `react-live` and `spectacle`).

so i don't think we should add these to the default set -- but we also fully support swapping out our vendored Prism for your own instance, which you could customize with any languages you need.

**Comment by schultzp2020** [comment]
@jpdriver I tried creating a vendored Prism but the type support breaks with [`index.d.ts is not a module`](https://www.npmjs.com/package/@schultzp2020/prism-react-renderer) if I modify the package and publish it. Further, I cannot copy the code snippet that is used in the library because it uses `fs`.

I've also tried manually adding the types and it does not work on React 18 with Next 12.2.
