### ISSUE TITLE
New language support?

### ISSUE THREAD

**Issue by thatguyjono94** [FormidableLabs/prism-react-renderer#22]
Hi, could you please show me how to construct a Prism object manually? I'm trying to get a few language supports that are not out of the box to the react package. Thanks.

**Comment by kitten** [comment]
There's probably two options that you have.

The **first** and easiest one is to use just the components you need and add them onto the vendored Prism in `prism-react-renderer. To do that you need to re-expose `Prism` as a global and then import a component from `prismjs/components/X.js`. Something like the following should work:

```js
import Prism from 'prism-react-renderer/prism';
(typeof global !== 'undefined' ? global : window).Prism = Prism;

require('prismjs/components/prism-java');
```

Which due to prismjs' use of globals inside the individual components files will pick up Prism from the global and add the new language on there (See: https://unpkg.com/prismjs@1.15.0/components/prism-java.js)

If you don't want to pollute your global namespace you could also do sth like what this library is doing on build, which is using a babel plugin like the `codegen.macro`. The code in here doesn't do much more than inline the Prism components' code in the correct order: https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/index.js

The **second** option is to just compose your own Prism instance. So you can either just import all of Prism or just the parts you need like so: https://github.com/FormidableLabs/react-live/blob/master/src/utils/prism.js#L1-L5

At that point you'd stop applying the `defaultProps` and not import those and pass a `theme` and `Prism` prop manually so that treeshaking removes the vendored Prism and throws it out off your bundle in favour of your custom one.

Hope this helps :) Let me know if you need more info

**Comment by thatguyjono94** [comment]
Thank you, I'll try constructing a manual Prism object manually. Will get back to you in a bit if it works, cheers.

**Comment by thatguyjono94** [comment]
@kitten I've tried constructing my own prism object from this link https://github.com/FormidableLabs/react-live/blob/master/src/utils/prism.js#L1-L5 and it returns me a the html code to inject in my div. After manually adding the .prism-code css I get a basic version working. The issue at the moment is I still don't get the language specific styling from the return of this function `const prism = (code, language = 'jsx') => highlight(code, languages[language]);`? I've imported the languages but still don't get the style.

**Comment by thatguyjono94** [comment]
Thanks @kitten, it all works perfect!

**Comment by jlesquembre** [comment]
@thatguyjono94 can you provide an example? I'm trying to adapt [this example](https://github.com/ChristopherBiscardi/gatsby-mdx/blob/379090494586c4b25e9ec4a490dfb324f1aad97e/examples/dato-cms-blog/src/components/code.js#L17-L29) to use my own Prism instance, but I don't get how

**Comment by vlsi** [comment]
I was trying to apply @kitten's  [approach](https://github.com/FormidableLabs/prism-react-renderer/issues/22#issuecomment-448398515) to my `mdx-deck` slides, however it did not work (the error was 'Prism is not defined')

However the following did work: https://github.com/pomber/code-surfer/issues/12#issuecomment-474939533

(cross-posting just in case others will find these issues)

**Comment by bravo-kernel** [comment]
@kitten I'm trying to add the `powershell` language to Docusaurus and would like to try your **option 2** but the link to the example has gone. Is it still around somewhere?

**Comment by sourabhv** [comment]
As @vlsi mentioned, you can use `refractor` (what `react-syntax-highlighter` uses) to add language support to Prism

```js
import Prism from 'prism-react-renderer/prism';
import dockerLang from 'refractor/lang/docker';
dockerLang(Prism);

// ...

<Highlight
  Prism={Prism}
  theme={<your theme or defaultProps.theme>}
  // ...
>

```

**Comment by caelinsutch** [comment]
Additionally, if you're doing this in Gatsby, add this to your `gatsby-browser.js` file:

```
import Prism from 'prism-react-renderer/prism';
import dartLang from 'refractor/lang/dart';
dartLang(Prism);
```

in similar style to @sourabhv

**Comment by chfritz** [comment]
The way to import `Prism` seems to have changed by now. Here is a working example for `bash`:
```jsx
import { Prism } from 'prism-react-renderer'
import bashLang from 'refractor/lang/bash';
bashLang(Prism);
```
