### ISSUE TITLE
Using Old Prism CSS Files

### ISSUE THREAD

**Issue by shellscape** [FormidableLabs/prism-react-renderer#223]
I cannot for the life of me figure out how to use old prism css files for theming. Doesn't look like there's any mention in the docs for that, just one line in the README which says that we can. What's the proper procedure to use those? For example: https://github.com/konnyakuxzy/prism-one-monokai/blob/master/prism-one-monokai.css

**Comment by severinlandolt** [comment]
Same problem here, despite passing `theme={undefined}`, the default theme gets applied.

**Comment by carloskelly13** [comment]
Hi :wave: The library will load the theme because it's key dictionary is required to know how to map the tokens properly. You can import a CSS file and have its styles apply. The easiest way is to pass an empty object to `style` for the token components.

Here is an example of what that could look like:

```
{tokens.map((line, i) => (
  <div key={i} {...getLineProps({ line })} style={{}}>
    <span className={styles.lineNumber}>{i + 1}</span>
      {line.map((token, key) => (
        <span key={key} {...getTokenProps({ token })} style={{}} />
      ))}
  </div>
))}
```
I imported the CSS file on our demo app in this repo and tried it out and the styles came through. We can update the docs to explain this approach.

<img width="1091" alt="Screenshot 2023-12-21 at 12 54 43 PM" src="https://github.com/FormidableLabs/prism-react-renderer/assets/1738349/416c78d3-33de-4a6b-967b-a479792c2292">

**Comment by severinlandolt** [comment]
Thanks a ton! @carloskelly13
