### ISSUE TITLE
Minor version breaking change

### ISSUE THREAD

**Issue by Kosai106** [FormidableLabs/prism-react-renderer#42]
See https://github.com/FormidableLabs/prism-react-renderer/pull/41 for details.

Essentially a minor version was pushed live with breaking changes to production builds.

This should have been released as a major change so automated build tools wouldn't automatically update. It has caused all sorts of issues in our automated testing over the past week now, which is not acceptable, even for OSS.

**Comment by kitten** [comment]
Hiya :wave: Sorry for the late reply.

So some languages were removed because of unrelated reasons. This package is mainly intended to support `react-live` and `spectacle`. That means that we didn't have any use for including all languages, hence the removal.

The full `Prism` library can always be included and replace the built-in one though.

This isn't strictly speaking non-semver-compliant, but indeed a breaking change. But `prism-react-renderer` is currently released as an `0.x.x` (which will change soon), so this applies: https://semver.org/#spec-item-4
