### ISSUE TITLE
Code block scroll bar

### ISSUE THREAD

**Issue by armstrongl** [FormidableLabs/prism-react-renderer#65]
Are there plans to add scrollbar functionality in the foreseeable future (or is there an existing way to do this)? We're running into an issue with large blocks of code overflowing the component, and I'd prefer to have a scrollbar than to wrap the text. 

Also, it appears that not all the in-line comments are being recognized. Do you have any insight into why this might be happening? 

![image](https://user-images.githubusercontent.com/29762984/74484283-e3537f00-4e7d-11ea-9402-15044861752e.png)

Thanks in advance! 😄

**Comment by kitten** [comment]
You should be able to use the usual overflow CSS properties to style your code blocks to achieve scrolling. We just choose not to impose too many defaults 👍

I’m not quite sure why these code comments aren’t being highlighted, but since we just use Prism it may be a small issue with a specific highlighting feature in their syntax?

If you have a code sample somewhere (maybe on CodeSandbox) I can take a look if you’d like 🙌

**Comment by AleksandrHovhannisyan** [comment]
Unfortunately, it seems this is still an issue

**Comment by KishanMandora** [comment]
I was facing the same issue but adding word-wrap and white-space solved your issue. 
Code: 
```css
 word-wrap: "break-word",
 white-space: "normal",
```
