### ISSUE TITLE
Themes shouldn't de-emphasise comments

### ISSUE THREAD

**Issue by Vinnl** [FormidableLabs/prism-react-renderer#86]
All included themes I tried display comments in a faded colour. This is not great in a regular editor use case (since comments are usually important to understand what's going on), but it's doubly troublesome in a documentation setting, e.g. a blog [or Docusaurus website](https://github.com/facebook/docusaurus/issues/2938) (which uses the Palenight theme by default).

![image](https://user-images.githubusercontent.com/4251/84687086-66c0d200-af3d-11ea-9718-23f300777a65.png)

Ideally (in my humble opinion), comments would be in a colour that stands out from the background and the rest of the text, having enough contrast to _at least_ meet the WCAG standards for accessible text.

(I'm not sure if the included themes are part of this project, but I couldn't find where they were from otherwise...)

**Comment by kitten** [comment]
They are part of this project, but they’re mostly auto-generated (and partly hand-modified) based on VSCode themes. Hence it’s not the responsibility of prism-react-tenderer to provide _different_ themes.

I’d be happy to merge PRs for more accessible variants of the theme that also take colour contrast, and not just comment colours into account.

But overall, I’m confident that the themes are a good baseline that people can customise since they’re just small configs ♥️
