### ISSUE TITLE
Next.js MDX not applying default styles

### ISSUE THREAD

**Issue by maxuuell** [FormidableLabs/prism-react-renderer#89]
Hello. 

I followed what was described in #53 for some rust code I wanted to highlight. But, I am trying to do it in next.js, and am not seeing the styles from the [prism docs](https://prismjs.com/examples.html) being applied. Seeing some base style being applied via style attributes, is all.

`<span class="token macro property" style="color: rgb(154, 134, 253);">format!</span>`

<img width="741" alt="Screen Shot 2020-08-14 at 4 29 46 PM" src="https://user-images.githubusercontent.com/13597248/90299589-6fedf280-de4b-11ea-857c-cd0e87cb436d.png">

I am only interested in getting the default style working. Any guidance on what I might be missing?

Going deeper, here is my CodeBlock component

```
import React from "react";
import Highlight, { defaultProps } from "prism-react-renderer";

const CodeBlock = ({ children }) => {
  return (
    <Highlight {...defaultProps} code={children} language={"rust"}>
      {({ className, styles, tokens, getLineProps, getTokenProps }) => {
        return (
          <pre className={className} styles={styles}>
            <code className={className}>
              {tokens.map((line, i) => (
                <div key={i} {...getLineProps({ line, key: i })}>
                  {line.map((token, key) => (
                    <span key={key} {...getTokenProps({ token, key })} />
                  ))}
                </div>
              ))}
            </code>
          </pre>
        );
      }}
    </Highlight>
  );
};

export default CodeBlock;
```

Here are the imports for my layout component that is taking care of rendering the MDX.

```
import React from "react";
import Prism from "prism-react-renderer/prism";
import { LayoutHeader } from "../components/Headers";
import HeadElement from "../components/HeadElement";
import { P, H1, H3 } from "../components/common";
import ConvertKitForm from "../components/ConvertKitForm";

(typeof global !== "undefined" ? global : window).Prism = Prism;

require("prismjs/components/prism-rust");

...component body...
```

**Comment by JonShort** [comment]
The code you posted looks good 👍, I wonder if the style differences might be because [this package includes duotoneDark as the default theme](https://github.com/FormidableLabs/prism-react-renderer#theming).

To use prism's default theme (which they provide as css), you may need to:

### 1). Stop this library applying it's default theme:

_set the theme prop as `undefined`_
```jsx
<Highlight {...defaultProps} code={children} language="rust" theme={undefined}>
```

### 2). Import the default prism css

```js
import "prismjs/themes/prism.css";
```
_*note* - you don't have to use the `prismjs` library, that was just the easiest way for me to do it for this example_

## Examples

I quickly created a sandbox showing this in-action: https://codesandbox.io/s/prism-react-renderer-example-forked-tybdb?file=/src/WithDefaultPrismTheme.js

Looks like there is a little section on this in [the FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq) too.

**Comment by maxuuell** [comment]
Thanks @JonShort for the quick response.  That did it.  Was able to get the default working, and was able to apply one of the prism themes 👍 

Looks like I needed to read the docs a bit more carefully 😅
