### ISSUE TITLE
Differences between Prism-React-Renderer and PrismJS?

### ISSUE THREAD

**Issue by TylerYep** [FormidableLabs/prism-react-renderer#97]
I'm quite confused on what exactly the difference is between this library's vendored Prism and the source PrismJS implementation. From the README it sounds like prism-react-renderer is equivalent to Prism for the subset of supported languages, but when I use it I get very different results from source PrismJS on a language like Python:

Could someone please clarify what the differences are? Is it possible to use the source PrismJS styles, for a more complete syntax highlighting?

Source PrismJS:
<img width="589" alt="Source PrismJS" src="https://user-images.githubusercontent.com/18021435/99364753-34f4c400-286b-11eb-873c-c831185108ac.png">

Prism-React-Renderer:
<img width="688" alt="Prism-React-Renderer" src="https://user-images.githubusercontent.com/18021435/99364805-45a53a00-286b-11eb-8684-a972fde7d212.png">

**Comment by kitten** [comment]
If you look at the exact things that are styled in your screenshots, you may actually notice that the same things are styled the same in just different ways. So you're not getting two different results, but you're using two different themes.

Some minor things may actually be different because the highlighting and token assignment are different between the vendored version and the mainline one. You can check the source; it's skimmed down but the main different is how tokens are split up between lines
