### ISSUE TITLE
Contentful and gatsby setup?

### ISSUE THREAD

**Issue by devquestionz** [FormidableLabs/prism-react-renderer#98]
Has anyone used this with contentful and gatsby? I can't get this to work

**Comment by devquestionz** [comment]
no one used this for contentful before?

**Comment by kitten** [comment]
I don't think this is a question for an issue tracker. I also think this doesn't really make sense to me. Contentful is a CMS, so the two topics here are a stretch.

Please try to find a message board like StackOverflow or similar to ask questions that are very general and off topic rather than an issue board. Sorry! 😅
